/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CookingClassRouteImport } from './routes/cooking-class'
import { Route as FotoRouteImport } from './routes/foto'
import { Route as GatheringRouteImport } from './routes/gathering'
import { Route as KegiatanBelajarRouteImport } from './routes/kegiatan-belajar'
import { Route as KegiatanProgramRouteImport } from './routes/kegiatan-program'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LegalitasRouteImport } from './routes/legalitas'
import { Route as PersyaratanRouteImport } from './routes/persyaratan'
import { Route as ProgramAupairRouteImport } from './routes/program-aupair'
import { Route as ProgramAusbildungRouteImport } from './routes/program-ausbildung'
import { Route as ProgramFsjRouteImport } from './routes/program-fsj'
import { Route as StrukturRouteImport } from './routes/struktur'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as VideoRouteImport } from './routes/video'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CookingClassRoute = CookingClassRouteImport.update({
  id: '/cooking-class',
  path: '/cooking-class',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoRoute = FotoRouteImport.update({
  id: '/foto',
  path: '/foto',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringRoute = GatheringRouteImport.update({
  id: '/gathering',
  path: '/gathering',
  getParentRoute: () => rootRouteImport,
} as any)
const KegiatanBelajarRoute = KegiatanBelajarRouteImport.update({
  id: '/kegiatan-belajar',
  path: '/kegiatan-belajar',
  getParentRoute: () => rootRouteImport,
} as any)
const KegiatanProgramRoute = KegiatanProgramRouteImport.update({
  id: '/kegiatan-program',
  path: '/kegiatan-program',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalitasRoute = LegalitasRouteImport.update({
  id: '/legalitas',
  path: '/legalitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PersyaratanRoute = PersyaratanRouteImport.update({
  id: '/persyaratan',
  path: '/persyaratan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramAupairRoute = ProgramAupairRouteImport.update({
  id: '/program-aupair',
  path: '/program-aupair',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramAusbildungRoute = ProgramAusbildungRouteImport.update({
  id: '/program-ausbildung',
  path: '/program-ausbildung',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramFsjRoute = ProgramFsjRouteImport.update({
  id: '/program-fsj',
  path: '/program-fsj',
  getParentRoute: () => rootRouteImport,
} as any)
const StrukturRoute = StrukturRouteImport.update({
  id: '/struktur',
  path: '/struktur',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cooking-class': typeof CookingClassRoute
  '/foto': typeof FotoRoute
  '/gathering': typeof GatheringRoute
  '/kegiatan-belajar': typeof KegiatanBelajarRoute
  '/kegiatan-program': typeof KegiatanProgramRoute
  '/kontak': typeof KontakRoute
  '/legalitas': typeof LegalitasRoute
  '/persyaratan': typeof PersyaratanRoute
  '/program-aupair': typeof ProgramAupairRoute
  '/program-ausbildung': typeof ProgramAusbildungRoute
  '/program-fsj': typeof ProgramFsjRoute
  '/struktur': typeof StrukturRoute
  '/team': typeof TeamRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cooking-class': typeof CookingClassRoute
  '/foto': typeof FotoRoute
  '/gathering': typeof GatheringRoute
  '/kegiatan-belajar': typeof KegiatanBelajarRoute
  '/kegiatan-program': typeof KegiatanProgramRoute
  '/kontak': typeof KontakRoute
  '/legalitas': typeof LegalitasRoute
  '/persyaratan': typeof PersyaratanRoute
  '/program-aupair': typeof ProgramAupairRoute
  '/program-ausbildung': typeof ProgramAusbildungRoute
  '/program-fsj': typeof ProgramFsjRoute
  '/struktur': typeof StrukturRoute
  '/team': typeof TeamRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cooking-class': typeof CookingClassRoute
  '/foto': typeof FotoRoute
  '/gathering': typeof GatheringRoute
  '/kegiatan-belajar': typeof KegiatanBelajarRoute
  '/kegiatan-program': typeof KegiatanProgramRoute
  '/kontak': typeof KontakRoute
  '/legalitas': typeof LegalitasRoute
  '/persyaratan': typeof PersyaratanRoute
  '/program-aupair': typeof ProgramAupairRoute
  '/program-ausbildung': typeof ProgramAusbildungRoute
  '/program-fsj': typeof ProgramFsjRoute
  '/struktur': typeof StrukturRoute
  '/team': typeof TeamRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cooking-class'
    | '/foto'
    | '/gathering'
    | '/kegiatan-belajar'
    | '/kegiatan-program'
    | '/kontak'
    | '/legalitas'
    | '/persyaratan'
    | '/program-aupair'
    | '/program-ausbildung'
    | '/program-fsj'
    | '/struktur'
    | '/team'
    | '/tentang-kami'
    | '/video'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cooking-class'
    | '/foto'
    | '/gathering'
    | '/kegiatan-belajar'
    | '/kegiatan-program'
    | '/kontak'
    | '/legalitas'
    | '/persyaratan'
    | '/program-aupair'
    | '/program-ausbildung'
    | '/program-fsj'
    | '/struktur'
    | '/team'
    | '/tentang-kami'
    | '/video'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cooking-class'
    | '/foto'
    | '/gathering'
    | '/kegiatan-belajar'
    | '/kegiatan-program'
    | '/kontak'
    | '/legalitas'
    | '/persyaratan'
    | '/program-aupair'
    | '/program-ausbildung'
    | '/program-fsj'
    | '/struktur'
    | '/team'
    | '/tentang-kami'
    | '/video'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CookingClassRoute: typeof CookingClassRoute
  FotoRoute: typeof FotoRoute
  GatheringRoute: typeof GatheringRoute
  KegiatanBelajarRoute: typeof KegiatanBelajarRoute
  KegiatanProgramRoute: typeof KegiatanProgramRoute
  KontakRoute: typeof KontakRoute
  LegalitasRoute: typeof LegalitasRoute
  PersyaratanRoute: typeof PersyaratanRoute
  ProgramAupairRoute: typeof ProgramAupairRoute
  ProgramAusbildungRoute: typeof ProgramAusbildungRoute
  ProgramFsjRoute: typeof ProgramFsjRoute
  StrukturRoute: typeof StrukturRoute
  TeamRoute: typeof TeamRoute
  TentangKamiRoute: typeof TentangKamiRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooking-class': {
      id: '/cooking-class'
      path: '/cooking-class'
      fullPath: '/cooking-class'
      preLoaderRoute: typeof CookingClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto': {
      id: '/foto'
      path: '/foto'
      fullPath: '/foto'
      preLoaderRoute: typeof FotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gathering': {
      id: '/gathering'
      path: '/gathering'
      fullPath: '/gathering'
      preLoaderRoute: typeof GatheringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kegiatan-belajar': {
      id: '/kegiatan-belajar'
      path: '/kegiatan-belajar'
      fullPath: '/kegiatan-belajar'
      preLoaderRoute: typeof KegiatanBelajarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kegiatan-program': {
      id: '/kegiatan-program'
      path: '/kegiatan-program'
      fullPath: '/kegiatan-program'
      preLoaderRoute: typeof KegiatanProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legalitas': {
      id: '/legalitas'
      path: '/legalitas'
      fullPath: '/legalitas'
      preLoaderRoute: typeof LegalitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persyaratan': {
      id: '/persyaratan'
      path: '/persyaratan'
      fullPath: '/persyaratan'
      preLoaderRoute: typeof PersyaratanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-aupair': {
      id: '/program-aupair'
      path: '/program-aupair'
      fullPath: '/program-aupair'
      preLoaderRoute: typeof ProgramAupairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-ausbildung': {
      id: '/program-ausbildung'
      path: '/program-ausbildung'
      fullPath: '/program-ausbildung'
      preLoaderRoute: typeof ProgramAusbildungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-fsj': {
      id: '/program-fsj'
      path: '/program-fsj'
      fullPath: '/program-fsj'
      preLoaderRoute: typeof ProgramFsjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/struktur': {
      id: '/struktur'
      path: '/struktur'
      fullPath: '/struktur'
      preLoaderRoute: typeof StrukturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CookingClassRoute: CookingClassRoute,
  FotoRoute: FotoRoute,
  GatheringRoute: GatheringRoute,
  KegiatanBelajarRoute: KegiatanBelajarRoute,
  KegiatanProgramRoute: KegiatanProgramRoute,
  KontakRoute: KontakRoute,
  LegalitasRoute: LegalitasRoute,
  PersyaratanRoute: PersyaratanRoute,
  ProgramAupairRoute: ProgramAupairRoute,
  ProgramAusbildungRoute: ProgramAusbildungRoute,
  ProgramFsjRoute: ProgramFsjRoute,
  StrukturRoute: StrukturRoute,
  TeamRoute: TeamRoute,
  TentangKamiRoute: TentangKamiRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
